# Site settings
title: UNIS Radio Club
email: UNISRadio@PlaceHolder.com
description: "Contact WebMasters(s): Andrei Aldea (16aaldea@unis.org), Timothy Cargan (15tcargan@unis.org)"
baseurl: ""
url: "http://UNISRadio.com"
twitter_username: RadioUNIS
github_username: UNIS-Radio/UNIS-Radio.github.io

# Build settings
markdown: kramdown
permalink: pretty
