# Site settings
title: UNIS Radio Club
email: radio@unis.org
description: "UNIS Radio"
baseurl: ""
url: "http://radio.unis.org"
twitter_username: RadioUNIS
github_username: UNIS-Radio/UNIS-Radio.github.io

# Build settings
markdown: kramdown
permalink: pretty
